### ISSUE TITLE
Discuss interface for pipeline

### ISSUE THREAD

**Issue by devoworm** [devoworm/GSoC-2017#28]

**Comment by sedflix** [comment]
1. First part will be a method to detect any interior region of each cell. We can provide multiple methods to do that. Some of the methods in my mind are Weka Trainable Segmentation Tool, Edge based tool and morphological tool. 
 - I will implement at least WTS method by 21 August.
 - The user will have to enter select a classifier model that has been made using WTS. 
 - After that user can threshold the probability map video we get from WTS. The method of thresholding can be a manual thresholding or Graph Cut. 

2. The second part will consist of manipulating(or evolving) the detected portion of each cell so that it represents the actual cell boundaries(This is where LevelSet is used extensively) *
 - The backend part of this is mostly done. But it still needs a lot of optimization*

3. The third part is going to be the analysis task. Given segmentation of cells in an embryo in some particular format, this part will analyze the segmentation to give the required result(the analytics data. - [ ] Yet to be decided)
